-- SI EXISTE LA DB FUTBOL, LA BORRA
DROP DATABASE IF EXISTS futbol;

-- CREAMOS LA DB FUTBOL
CREATE DATABASE futbol;
-- INDICAMOS QUE USE ESA DB
USE futbol;

-- DENTRO DE FUTBOL CREAMOS LA TABLA EQUIPOS Y AHI DENTRO PONEMOS
-- EL CONTENIDO DE LAS TABLAS Y SUS TIPOS DE DATOS
CREATE TABLE Equipos (
	ID INT PRIMARY KEY,
	Nombre VARCHAR(20),
	Ciudad VARCHAR(20),
	Champions INT
);

-- CREAMOS LA TABLA DE JUGADORES CON SU CONTENIDO Y TIPO DE DATOS
CREATE TABLE Jugadores (
	DNI VARCHAR(20) PRIMARY KEY,
	Nombre VARCHAR(50),
	Nacionalidad VARCHAR(20),
	Dorsal INT,
	Altua FLOAT,
	ID_Equipo INT,
	FOREIGN KEY (ID_Equipo) REFERENCES Equipos(ID)
);

-- DENTRO DE LA BASE DE DATOS EQUIPOS, INTRODUCIMOS EN ORDEN LOS VALORES DE LAS COLUMNAS, QUE SE ALMACENARÁN DENTRO DE LOS CAMPOS CORRESPONDIENTES
INSERT INTO Equipos VALUES (1,'Real Madrid', 'Madrid', 15);
INSERT INTO Equipos VALUES (2, 'Atlético de Madrid', 'Madrid', 0);

-- LO MISMO DE ANTES PERO EN LA DB DE JUGADORES
INSERT INTO Jugadores VALUES
('12433235B', 'Vinicius Jr', 'Brasileña', 7, 1.78, 1),
('32950441D', 'Kylian Mbappé', 'Francés/Senegalés', 9, 1.84, 1);
